on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test-doc:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1